server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server: 
        native:
          search-locations: "classpath:/config"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
