services:
  network-deploy-service:
    networks:
      - mmmut

  microservice-base-config:
    extends:
      service: network-deploy-service
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/