spring:
  application:
    name: "api-gateway"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # default route locator wont allow
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "api-gateway"
    description: "Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      smartmind:
        gateway: DEBUG